apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echoservice-virtualservice
spec:
  hosts:
    - echoserver
  http:
    - route:
        - destination:
            host: echoserver
            subset: echoserver-v1
            port:
              number: 80
          weight: 50
        - destination:
            host: echoserver
            subset: echoserver-v2
            port:
              number: 80
          weight: 50

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: proxy-app-virtualservice
spec:
  hosts:
    - arch.homework
  gateways:
    - proxy-app-gateway
  http:
    - route:
        - destination:
            host: proxy-app
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blackhole-virtualservice
spec:
  hosts:
    - arch.homework
  http:
    - route:
        - destination:
            host: blackhole
            port:
              number: 80